version: '3.7'  

services:  
    php:
        build: ./docker/php/
        environment:
            TIMEZONE: Europe/Moscow
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
            - ./app:/var/www/app
        working_dir: /var/www/app

    webserver:
        image: nginx:1.11
        depends_on:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:80

    postgres:
        image: postgres:10.6
        ports:
            - '5432:5432'
        container_name: 'postgresql'
        working_dir: /app
        restart: always
        environment:
            POSTGRES_DB: 'db_name'
            POSTGRES_USER: 'db_user'
            POSTGRES_PASSWORD: 'db_pass'
        volumes:
            - ./data/dump:/app/dump
            - ./data/postgresql:/var/lib/postgresql/data

    composer:
        image: composer:1.4
        volumes_from:
            - php
        working_dir: /var/www/app